// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerAdministration.Server.DataAccess.DbContexts;

namespace ServerAdministration.Server.DataAccess.Migrations.Slave
{
    [DbContext(typeof(SlaveDbContext))]
    [Migration("20190611112351_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ServerAdministration.Server.Entities.IISLogEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientIp");

                    b.Property<string>("Computername");

                    b.Property<string>("Cookie");

                    b.Property<DateTime>("DateTimeEvent");

                    b.Property<string>("Host");

                    b.Property<string>("Method");

                    b.Property<int?>("ProtocolStatus");

                    b.Property<int?>("ProtocolSubstatus");

                    b.Property<string>("ProtocolVersion");

                    b.Property<int?>("RecievedBytes");

                    b.Property<string>("Referer");

                    b.Property<int?>("SentBytes");

                    b.Property<string>("ServerIp");

                    b.Property<int?>("ServerPort");

                    b.Property<string>("Sitename");

                    b.Property<int?>("TimeTaken");

                    b.Property<string>("UriQuery");

                    b.Property<string>("UriStem");

                    b.Property<string>("UserAgent");

                    b.Property<string>("Username");

                    b.Property<long?>("Win32Status");

                    b.HasKey("Id");

                    b.ToTable("IISLogEvents");
                });

            modelBuilder.Entity("ServerAdministration.Server.Entities.SiteIISLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("IISLogEventId");

                    b.Property<string>("SiteAppPath");

                    b.Property<int>("SlaveServerId");

                    b.HasKey("Id");

                    b.HasIndex("IISLogEventId");

                    b.ToTable("SiteIISLogs");
                });

            modelBuilder.Entity("ServerAdministration.Server.Entities.SiteIISLog", b =>
                {
                    b.HasOne("ServerAdministration.Server.Entities.IISLogEvent", "IISLogEvent")
                        .WithMany()
                        .HasForeignKey("IISLogEventId");
                });
#pragma warning restore 612, 618
        }
    }
}
